import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    AUTH_SECRET: z.string().min(16),
    AUTH_URL: z.string().url().optional(),
    AUTH_GOOGLE_ID: z.string().optional(),
    AUTH_GOOGLE_SECRET: z.string().optional(),
    AUTH_RESEND_KEY: z.string().optional(),
    AUTH_EMAIL_FROM: z.string().optional(),
    CONTACT_TO_EMAIL: z.string().email().optional(),
    UPSTASH_REDIS_REST_URL: z.string().url().optional(),
    UPSTASH_REDIS_REST_TOKEN: z.string().optional(),
    UPLOADTHING_SECRET: z.string().optional(),
    UPLOADTHING_APP_ID: z.string().optional(),
    SENTRY_DSN: z.string().optional(),
    NODE_ENV: z
      .enum(["development", "test", "production"])
      .default("development"),
    BILLING_ENABLED: z.string().optional(),
    STRIPE_ENABLED: z.string().optional(),
    PAYDUNYA_ENABLED: z.string().optional(),
    PAYTECH_ENABLED: z.string().optional(),
    PAYTECH_API_KEY: z.string().optional(),
    PAYTECH_API_SECRET: z.string().optional(),
    PAYTECH_ENV: z.string().optional(),
    STRIPE_SECRET_KEY: z.string().optional(),
    STRIPE_WEBHOOK_SECRET: z.string().optional(),
    PAYDUNYA_MODE: z.enum(["test", "live"]).optional(),
    PAYDUNYA_MASTER_KEY: z.string().optional(),
    PAYDUNYA_PRIVATE_KEY: z.string().optional(),
    PAYDUNYA_PUBLIC_KEY: z.string().optional(),
    PAYDUNYA_TOKEN: z.string().optional(),
    CRON_SECRET: z.string().optional(),
    STRIPE_PRICE_PRO_MONTHLY: z.string().optional(),
    STRIPE_PRICE_PRO_ANNUAL: z.string().optional(),
    STRIPE_PRICE_ENTERPRISE_MONTHLY: z.string().optional(),
    STRIPE_PRICE_ENTERPRISE_ANNUAL: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().url(),
    NEXT_PUBLIC_SENTRY_DSN: z.string().optional(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    AUTH_URL: process.env.AUTH_URL,
    AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET,
    AUTH_RESEND_KEY: process.env.AUTH_RESEND_KEY,
    AUTH_EMAIL_FROM: process.env.AUTH_EMAIL_FROM,
    CONTACT_TO_EMAIL: process.env.CONTACT_TO_EMAIL,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    UPLOADTHING_SECRET: process.env.UPLOADTHING_SECRET,
    UPLOADTHING_APP_ID: process.env.UPLOADTHING_APP_ID,
    SENTRY_DSN: process.env.SENTRY_DSN,
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    BILLING_ENABLED: process.env.BILLING_ENABLED,
    STRIPE_ENABLED: process.env.STRIPE_ENABLED,
    PAYDUNYA_ENABLED: process.env.PAYDUNYA_ENABLED,
    PAYTECH_ENABLED: process.env.PAYTECH_ENABLED,
    PAYTECH_API_KEY: process.env.PAYTECH_API_KEY,
    PAYTECH_API_SECRET: process.env.PAYTECH_API_SECRET,
    PAYTECH_ENV: process.env.PAYTECH_ENV,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    PAYDUNYA_MODE: process.env.PAYDUNYA_MODE,
    PAYDUNYA_MASTER_KEY: process.env.PAYDUNYA_MASTER_KEY,
    PAYDUNYA_PRIVATE_KEY: process.env.PAYDUNYA_PRIVATE_KEY,
    PAYDUNYA_PUBLIC_KEY: process.env.PAYDUNYA_PUBLIC_KEY,
    PAYDUNYA_TOKEN: process.env.PAYDUNYA_TOKEN,
    CRON_SECRET: process.env.CRON_SECRET,
    STRIPE_PRICE_PRO_MONTHLY: process.env.STRIPE_PRICE_PRO_MONTHLY,
    STRIPE_PRICE_PRO_ANNUAL: process.env.STRIPE_PRICE_PRO_ANNUAL,
    STRIPE_PRICE_ENTERPRISE_MONTHLY: process.env.STRIPE_PRICE_ENTERPRISE_MONTHLY,
    STRIPE_PRICE_ENTERPRISE_ANNUAL: process.env.STRIPE_PRICE_ENTERPRISE_ANNUAL,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
